################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2

# [fr]
# languageName = "Fr"
# languageCode = "fr"
# contentDir = "content/french"
# weight = 1
