############# Navigation en français ##############

# Menu principal
[[main]]
name = "Qu'est ce que la TAQ?"
weight = 1
url = "/about"

[[main]]
parent = "Qu'est ce que la TAQ?"
name = "À propos"
url = "/about"

[[main]]
parent = "Qu'est ce que la TAQ?"
name = "Historique"
url = "/history"

[[main]]
parent = "Qu'est ce que la TAQ?"
name = "Mission & objectifs"
url = "/mission-objectives"

[[main]]
parent = "Qu'est ce que la TAQ?"
name = "Comité de direction"
url = "/steering-committee"

[[main]]
parent = "Qu'est ce que la TAQ?"
name = "Gouvernance"
url = "/governance"

# Services en ADNe
[[main]]
name = "Services en ADNe"
weight = 2

[[main]]
parent = "Services en ADNe"
name = "Échantillonnage"
url = "/sampling"

[[main]]
parent = "Services en ADNe"
name = "Analyses de laboratoire"
url = "/laboratory-analysis"

[[main]]
parent = "Services en ADNe"
name = "Traitement de données"
url = "/data-processing"

[[main]]
parent = "Services en ADNe"
name = "Formation"
url = "/training"

[[main]]
parent = "Services en ADNe"
name = "L'ADNe, c'est quoi ?"
url = "/adne"

# Membres
[[main]]
name = "Membres"
weight = 3

[[main]]
parent = "Membres"
name = "Structure"
url = "/members/structure"

[[main]]
parent = "Membres"
name = "Liste des membres"
url = "/members/list"

[[main]]
parent = "Membres"
name = "Devenir membre"
url = "/members/become-a-member"

# Actualités
[[main]]
name = "Actualités"
url = "/news"
weight = 4

# Contact
[[main]]
name = "Contact"
url = "/contact"
weight = 5
