############# English navigation ##############

# Main menu
[[main]]
name = "What's the TAQ?"
weight = 1
url = "/"

[[main]]
parent = "What's the TAQ?"
name = "Mission"
weight = 10
url = "/"

[[main]]
parent = "What's the TAQ?"
name = "Governance"
weight = 20
url = "/governance"

[[main]]
parent = "What's the TAQ?"
name = "History"
weight = 30
url = "/history"

# [[main]]
# parent = "What's the TAQ?"
# name = "Steering Committee"
# weight = "40"
# url = "/steering-committee"

# Documentation
[[main]]
name = "Documentation"
url = "/documentation"
weight = 4

# ADNe Services
[[main]]
name = "ADNe Services"
weight = 2

[[main]]
parent = "ADNe Services"
name = "What is ADNe?"
weight=10
url = "/adne"

[[main]]
parent = "ADNe Services"
name = "Sampling"
weight=20
url = "/sampling"

[[main]]
parent = "ADNe Services"
name = "Laboratory Analysis"
weight=30
url = "/laboratory-analysis"

[[main]]
parent = "ADNe Services"
name = "Data Processing"
weight=40
url = "/data-processing"

[[main]]
parent = "ADNe Services"
name = "Training"
weight=50
url = "/training"

# Members
[[main]]
name = "Members"
weight = 3

[[main]]
parent = "Members"
name = "Member list"
url = "/members/list"

[[main]]
parent = "Members"
name = "Become a Member"
url = "https://forms.gle/WCvUnvtjezjfU8x37"
rel = 'external'

# News
[[main]]
name = "News"
url = "/news"
weight = 4


# footer menu
[[footer]]
name = "qPCR catalog"
url = ""
weight = 2

[[footer]]
name = "Visual identity"
url = ""
weight = 3


[[footer]]
name = "Contact"
url = "/contact"
weight = 4

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 5
