############# English navigation ##############

# Main menu
[[main]]
name = "What's the TAQc?"
weight = 1
url = "#"

[[main]]
parent = "What's the TAQc?"
name = "Mission"
weight = 11
url = "/"

[[main]]
parent = "What's the TAQc?"
name = "Committees"
weight = 12
url = "/committees"

[[main]]
parent = "What's the TAQc?"
name = "Governance"
weight = 13
url = "/governance"

# News
[[main]]
parent = "What's the TAQc?"
name = "News"
url = "/news"
weight = 14


[[main]]
parent = "What's the TAQc?"
name = "History"
weight = 15
url = "/history"

# What is eDNA?
[[main]]
name = "What's eDNA?"
weight = 2
url = "/adne"

# Services
[[main]]
name = "Services"
weight = 3
url = "#"

[[main]]
parent = "Services"
name = "Training"
weight = 31
url = "/training"

[[main]]
parent = "Services"
name = "Sampling"
weight = 32
url = "/sampling"

[[main]]
parent = "Services"
name = "Laboratory Analysis"
weight = 33
url = "/laboratory-analysis"

[[main]]
parent = "Services"
name = "Data storage and processing"
weight = 34
url = "/data-processing"

[[main]]
parent = "Services"
name = "Service provider list"
weight = 36
url = "/providers/list"

# Documentation
[[main]]
name = "Documentation"
weight = 4

[[main]]
parent = "Documentation"
name = "Protocols"
weight = 41
url = "/protocols"

[[main]]
parent = "Documentation"
name = "Standards"
weight = 42
url = "/standards"

# footer menu
[[footer]]
name = "Careers"
url = "/careers"
weight = 3

[[footer]]
name = "Contact"
url = "/contact"
weight = 4

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 5
