############# Navigation en français ##############

# Menu principal
[[main]]
name = "Qu'est-ce que la TAQc?"
weight = 1
url = "#"

[[main]]
parent = "Qu'est-ce que la TAQc?"
name = "Mission"
weight = 11
url = "/"

[[main]]
parent = "Qu'est-ce que la TAQc?"
name = "Comités"
weight = 12
url = "/committees"

[[main]]
parent = "Qu'est-ce que la TAQc?"
name = "Gouvernance"
weight = 13
url = "/governance"

[[main]]
parent = "Qu'est-ce que la TAQc?"
name = "Historique"
weight = 14
url = "/history"

# Documentation
# Documentation
[[main]]
name = "Documentation"
weight = 5

[[main]]
parent = "Documentation"
name = "Protocoles"
weight = 51
url = "/protocols"

[[main]]
parent = "Documentation"
name = "Standards"
weight = 52
url = "/standards"

# Services
[[main]]
name = "Services"
weight = 2

[[main]]
parent = "Services"
name = "Qu'est-ce que l'ADNe ?"
weight= 21
url = "/adne"

[[main]]
parent = "Services"
name = "Échantillonnage"
weight = 22
url = "/sampling"

[[main]]
parent = "Services"
name = "Analyses en laboratoire"
weight= 23
url = "/laboratory-analysis"

[[main]]
parent = "Services"
name = "Traitement et stockage des données"
weight= 24
url = "/data-processing"

[[main]]
parent = "Services"
name = "Formation"
weight= 25
url = "/training"

[[main]]
parent = "Services"
name = "S'inscrire comme fournisseur de services"
weight = 26
url = "/service-provider-registration"

# Actualités
[[main]]
name = "Actualités"
url = "/news"
weight = 4

# Menu de pied de page
[[footer]]
name = "Carrières"
url = "/careers"
weight = 3

[[footer]]
name = "Contact"
url = "/contact"
weight = 4

[[footer]]
name = "Politique de confidentialité"
url = "/privacy-policy"
weight = 5
