############# Navigation en français ##############

# Menu principal
[[main]]
name = "Qu'est-ce que la TAQc?"
weight = 1
url = "#"

[[main]]
parent = "Qu'est-ce que la TAQc?"
name = "Mission"
weight = 11
url = "/"

[[main]]
parent = "Qu'est-ce que la TAQc?"
name = "Comités"
weight = 12
url = "/committees"

[[main]]
parent = "Qu'est-ce que la TAQc?"
name = "Gouvernance"
weight = 13
url = "/governance"

# Actualités
[[main]]
parent = "Qu'est-ce que la TAQc?"
name = "Actualités"
url = "/news"
weight = 14


[[main]]
parent = "Qu'est-ce que la TAQc?"
name = "Historique"
weight = 15
url = "/history"

# Qu'est-ce que l'ADNe ?
[[main]]
name = "Qu'est-ce que l'ADNe ?"
weight = 2
url = "/adne"

# Services
[[main]]
name = "Services"
weight = 3

[[main]]
parent = "Services"
name = "Formation"
weight= 31
url = "/training"

[[main]]
parent = "Services"
name = "Échantillonnage"
weight = 32
url = "/sampling"

[[main]]
parent = "Services"
name = "Analyses en laboratoire"
weight= 33
url = "/laboratory-analysis"

[[main]]
parent = "Services"
name = "Traitement et stockage des données"
weight= 34
url = "/data-processing"

[[main]]
parent = "Services"
name = "Bottin des fournisseurs de services"
weight = 36
url = "/providers/list"

# Documentation
[[main]]
name = "Documentation"
weight = 4

[[main]]
parent = "Documentation"
name = "Protocoles"
weight = 41
url = "/protocols"

[[main]]
parent = "Documentation"
name = "Standards"
weight = 42
url = "/standards"

# Menu de pied de page
[[footer]]
name = "Carrières"
url = "/careers"
weight = 3

[[footer]]
name = "Contact"
url = "/contact"
weight = 4

[[footer]]
name = "Politique de confidentialité"
url = "/privacy-policy"
weight = 5
