############# English navigation ##############

# Main menu
[[main]]
name = "What's the TAQc?"
weight = 1
url = "#"

[[main]]
parent = "What's the TAQc?"
name = "Mission"
weight = 11
url = "/"

[[main]]
parent = "What's the TAQc?"
name = "Committees"
weight = 12
url = "/committees"

[[main]]
parent = "What's the TAQc?"
name = "Governance"
weight = 13
url = "/governance"

[[main]]
parent = "What's the TAQc?"
name = "History"
weight = 14
url = "/history"


# Documentation
[[main]]
name = "Documentation"
url = "/documentation"
weight = 5


# ADNe Services
[[main]]
name = "ADNe Services"
weight = 2
url = "#"

[[main]]
parent = "ADNe Services"
name = "What is ADNe?"
weight = 21
url = "/adne"

[[main]]
parent = "ADNe Services"
name = "Sampling"
weight = 22
url = "/sampling"

[[main]]
parent = "ADNe Services"
name = "Laboratory Analysis"
weight = 23
url = "/laboratory-analysis"

[[main]]
parent = "ADNe Services"
name = "Data storage and processing"
weight = 24
url = "/data-processing"

[[main]]
parent = "ADNe Services"
name = "Training"
weight = 25
url = "/training"

[[main]]
parent = "ADNe Services"
name = "Register as a service provider"
weight = 26
url = "/service-provider-registration"

# Members
[[main]]
name = "Members"
weight = 3
url = "#"

[[main]]
parent = "Members"
name = "Members List"
weight = 31
url = "/members/list"

[[main]]
parent = "Members"
name = "Become a Member"
weight = 32
url = "/become-a-member"

# News
[[main]]
name = "News"
url = "/news"
weight = 4

# footer menu
[[footer]]
name = "Careers"
url = "/careers"
weight = 3

[[footer]]
name = "Contact"
url = "/contact"
weight = 4

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 5
